replicaCount: 1

image:
  repository: base.med.thu/public/rstudio
  pullPolicy: Always
  tag: "v1"

containerName: "mywork"

service:
  type: ClusterIP
  port: 8888

resources:
  limits:
    cpu: "50"
    memory: "50"

# habor镜像库下载密钥
imageCredentials:
  registry: base.med.thu
  username: zhanghuming
  password: mima

# 载入数据位置
loadDataPath:
  public:
    - "input"
    - "lessonPublic"
  personal:
    - "zhanghuming"

type: centos

nfs: "Aries"

transfer: false
