name: Rust Build & Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  PROJECT_NAME: thumed_helper

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-x86   # Intel macOS runner
            target: x86_64-apple-darwin
          - os: macos-arm   # Apple Silicon runner
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v4

      # - name: Install Rust
      #   uses: dtolnay/rust-toolchain@stable
      #   with:
      #     targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: target/${{ matrix.target }}/release/*
